/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.joaodev.it_equipment_manager.view;

import com.joaodev.it_equipment_manager.model.Equipamento;
import com.joaodev.it_equipment_manager.model.TipoEquipamento;
import com.joaodev.it_equipment_manager.service.EquipamentoService;
import java.util.UUID;

public class TelaAtualizar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAtualizar.class.getName());
    private static EquipamentoService equipamentoService;

    /**
     * Creates new form TelaAtualizar
     */
    public TelaAtualizar(EquipamentoService equipamentoService) {
        this.equipamentoService = equipamentoService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAtualizar = new javax.swing.JButton();
        txtAtualizarModelo = new javax.swing.JLabel();
        txtAtualizarFabricante = new javax.swing.JLabel();
        txtAtualizarTipo = new javax.swing.JLabel();
        fldAtualizarModelo = new javax.swing.JTextField();
        fldAtualizarFabricante = new javax.swing.JTextField();
        fldAtualizarTipo = new javax.swing.JTextField();
        fldBuscarId = new javax.swing.JTextField();
        txtBuscarId = new javax.swing.JLabel();
        btLimparAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(this::btAtualizarActionPerformed);

        txtAtualizarModelo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtAtualizarModelo.setText("Insira o Modelo do Equipamento");

        txtAtualizarFabricante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtAtualizarFabricante.setText("Insira o Fabricante do Equipamento");

        txtAtualizarTipo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtAtualizarTipo.setText("Insira o Tipo do Equipamento");

        fldAtualizarModelo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        fldAtualizarModelo.addActionListener(this::fldAtualizarModeloActionPerformed);

        fldAtualizarFabricante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        fldAtualizarTipo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        fldBuscarId.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtBuscarId.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtBuscarId.setText("Insira o ID ao qual os dados serão atualizados");

        btLimparAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btLimparAtualizar.setText("Limpar");
        btLimparAtualizar.addActionListener(this::btLimparAtualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAtualizarModelo)
                            .addComponent(txtAtualizarFabricante)
                            .addComponent(txtAtualizarTipo)
                            .addComponent(txtBuscarId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fldBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fldAtualizarTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fldAtualizarFabricante, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fldAtualizarModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(btAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btLimparAtualizar)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAtualizarModelo)
                    .addComponent(fldAtualizarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAtualizarFabricante)
                    .addComponent(fldAtualizarFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAtualizarTipo)
                    .addComponent(fldAtualizarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAtualizar)
                    .addComponent(btLimparAtualizar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldAtualizarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAtualizarModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAtualizarModeloActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        try {
            UUID id = UUID.fromString(fldBuscarId.getText());

            Equipamento equipamento = new Equipamento();
            
            equipamento.setModelo(fldAtualizarModelo.getText());
            equipamento.setFabricante(fldAtualizarFabricante.getText());
            equipamento.setTipoEquipamento(TipoEquipamento.valueOf(fldAtualizarTipo.getText().toUpperCase()));

            Equipamento atualizado = equipamentoService.atualizarPorId(id, equipamento);

            javax.swing.JOptionPane.showMessageDialog(this, "Equipamento " + atualizado.getModelo() + " atualizado com sucesso!");
        }
        catch (IllegalArgumentException exc){
            javax.swing.JOptionPane.showMessageDialog(this, "ID ou tipo de equipamento inválido!");
        }
        catch (RuntimeException exc){
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + exc.getMessage());
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btLimparAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparAtualizarActionPerformed
        fldBuscarId.setText("");
        fldAtualizarModelo.setText("");
        fldAtualizarFabricante.setText("");
        fldAtualizarTipo.setText("");
        fldBuscarId.requestFocus();
    }//GEN-LAST:event_btLimparAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAtualizar(equipamentoService).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btLimparAtualizar;
    private javax.swing.JTextField fldAtualizarFabricante;
    private javax.swing.JTextField fldAtualizarModelo;
    private javax.swing.JTextField fldAtualizarTipo;
    private javax.swing.JTextField fldBuscarId;
    private javax.swing.JLabel txtAtualizarFabricante;
    private javax.swing.JLabel txtAtualizarModelo;
    private javax.swing.JLabel txtAtualizarTipo;
    private javax.swing.JLabel txtBuscarId;
    // End of variables declaration//GEN-END:variables
}
