/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.joaodev.it_equipment_manager.view;

import com.joaodev.it_equipment_manager.model.Equipamento;
import com.joaodev.it_equipment_manager.model.TipoEquipamento;
import com.joaodev.it_equipment_manager.service.EquipamentoService;
import java.util.NoSuchElementException;
import org.springframework.stereotype.Component;
import java.util.UUID;
import java.util.Optional;
import org.springframework.dao.DataIntegrityViolationException;

@Component
public class TelaEquipamento extends javax.swing.JFrame {
    
    private static EquipamentoService equipamentoService;
    private static TelaAtualizar telaAtualizar;

    private TelaEquipamento(EquipamentoService equipamentoService) {
        this.equipamentoService = equipamentoService;
        initComponents();
    }
    
    public static TelaAtualizar getTelaAtualizar(){
        if(telaAtualizar == null){
            telaAtualizar = new TelaAtualizar(equipamentoService);
        }
        
        return telaAtualizar;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEquipamento.class.getName());
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtModelo = new javax.swing.JLabel();
        fldModelo = new javax.swing.JTextField();
        fldFabricante = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JLabel();
        fldTipoEquipamento = new javax.swing.JTextField();
        txtTipoEquipamento = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        fldInserirId = new javax.swing.JTextField();
        txtInserirId = new javax.swing.JLabel();
        fldResultadoModelo = new javax.swing.JTextField();
        fldResultadoFabricante = new javax.swing.JTextField();
        fldResultadoTipo = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btIrAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtModelo.setText("Insira o Modelo do Equipamento");

        fldModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        fldFabricante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtFabricante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFabricante.setText("Insira o Fabricante do Equipamento");

        fldTipoEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTipoEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTipoEquipamento.setText("Insira o Tipo do Equipamento");

        btSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(this::btSalvarActionPerformed);

        btRemover.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btRemover.setText("Remover");
        btRemover.addActionListener(this::btRemoverActionPerformed);

        btBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(this::btBuscarActionPerformed);

        fldInserirId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fldInserirId.addActionListener(this::fldInserirIdActionPerformed);

        txtInserirId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtInserirId.setText("Insira o ID para Buscar ou Remover");

        fldResultadoFabricante.addActionListener(this::fldResultadoFabricanteActionPerformed);

        btLimpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(this::btLimparActionPerformed);

        btIrAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btIrAtualizar.setText("Atualizar...");
        btIrAtualizar.addActionListener(this::btIrAtualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTipoEquipamento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fldFabricante, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fldTipoEquipamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fldModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(txtInserirId)
                        .addGap(18, 18, 18)
                        .addComponent(fldInserirId, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fldResultadoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fldResultadoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fldResultadoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRemover)
                            .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btIrAtualizar)
                .addGap(262, 262, 262))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo)
                    .addComponent(fldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFabricante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldTipoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoEquipamento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIrAtualizar)
                    .addComponent(btSalvar))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInserirId)
                    .addComponent(fldInserirId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fldResultadoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldResultadoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldResultadoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            Equipamento novoObj = new Equipamento();

            novoObj.setModelo(fldModelo.getText());
            novoObj.setFabricante(fldFabricante.getText());
            novoObj.setTipoEquipamento(TipoEquipamento.valueOf(fldTipoEquipamento.getText().toUpperCase()));

            Equipamento salvo = equipamentoService.salvar(novoObj);

            javax.swing.JOptionPane.showMessageDialog(this, "Equipamento " + salvo.getModelo() + " cadastrado com sucesso!");

            fldModelo.setText("");
            fldFabricante.setText("");
            fldTipoEquipamento.setText("");
        }
        catch(IllegalArgumentException exc){
            javax.swing.JOptionPane.showMessageDialog(this, "Tipo de equipamento inválido!");
        }
        catch(NoSuchElementException exc){
            javax.swing.JOptionPane.showMessageDialog(this, "Registro não encontrado!");
        }
        catch (DataIntegrityViolationException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Já existe um equipamento com esses dados.");
        }
        catch (RuntimeException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao acessar o banco de dados.");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        try {
            UUID id = UUID.fromString(fldInserirId.getText());

            equipamentoService.remover(id);

            javax.swing.JOptionPane.showMessageDialog(this, "Equipamento removido com sucesso!");
        }
        catch (IllegalArgumentException exc){
            javax.swing.JOptionPane.showMessageDialog(this, "Tipo de equipamento inválido!");
        }
        catch(RuntimeException exc){
            javax.swing.JOptionPane.showMessageDialog(this, exc.getMessage());
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void fldInserirIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldInserirIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldInserirIdActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        try{
            UUID id = UUID.fromString(fldInserirId.getText());
            
            Optional<Equipamento> retorno = equipamentoService.buscarPorId(id);
            
            if(retorno.isPresent()){
                Equipamento eq = retorno.get();
                
                fldResultadoModelo.setText(eq.getModelo());
                fldResultadoFabricante.setText(eq.getFabricante());
                fldResultadoTipo.setText(eq.getTipoEquipamento().name());
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Esse ID não existe no Banco de Dados!");
            }
        }
        catch(IllegalArgumentException exc){
            javax.swing.JOptionPane.showMessageDialog(this, "ERRO - UUID Invállido!");
        }
        catch(RuntimeException exc){
            javax.swing.JOptionPane.showMessageDialog(this, exc.getMessage());
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void fldResultadoFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldResultadoFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldResultadoFabricanteActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btIrAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrAtualizarActionPerformed
        getTelaAtualizar().setLocationRelativeTo(this);
        TelaEquipamento.getTelaAtualizar().setVisible(true);
    }//GEN-LAST:event_btIrAtualizarActionPerformed
    
    public void limpar(){
        fldInserirId.setText("");
        fldResultadoModelo.setText("");
        fldResultadoFabricante.setText("");
        fldResultadoTipo.setText("");
        
        fldModelo.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btIrAtualizar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField fldFabricante;
    private javax.swing.JTextField fldInserirId;
    private javax.swing.JTextField fldModelo;
    private javax.swing.JTextField fldResultadoFabricante;
    private javax.swing.JTextField fldResultadoModelo;
    private javax.swing.JTextField fldResultadoTipo;
    private javax.swing.JTextField fldTipoEquipamento;
    private javax.swing.JLabel txtFabricante;
    private javax.swing.JLabel txtInserirId;
    private javax.swing.JLabel txtModelo;
    private javax.swing.JLabel txtTipoEquipamento;
    // End of variables declaration//GEN-END:variables
}
